### ISSUE TITLE
apptainer run fail with "thread 'main' panicked at helixer_post_bin/src/main.rs:30:10:"

### ISSUE THREAD

**Issue by tinyfallen** [gglyptodon/helixer-docker#12]
Hi dear developers,

Thanks for your work!
I have tried 0.3.4 version using apptainer, it failed with "thread 'main' panicked at helixer_post_bin/src/main.rs:30:10:". Please see details in the log file. [helixer034.log](https://github.com/user-attachments/files/18258712/helixer034.log)
By the way, version 0.3.3 works fine.

Best regards.

**Comment by tinyfallen** [comment]
maybe it was related to lzf incompatible
